name: 'atlas-github-action'
description: 'Create Atlas Cluster'
inputs:
  projectId: 
    description: 'project id'
    required: true
  name:
    description: 'cluster name'
    required: true
  reuse:
    default: "false"
    description: 'Reuse existing cluster without creating new one'
outputs:
  connectionURL: # output will be available to future steps
    description: 'connectionURL to the mongodb server'
runs:
  using: 'node16'
  main: 'dist/index.js'
