name: "build"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci 
    - run: npm run lint
