name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: createCluster
      with:
        ## Project ID
        projectId: ${{ secrets.PROJECTID }}
        ## Name of cluster
        name: ${{ secrets.CLUSTER_NAME }}
        ## Validates atlas credentials without creating cluster
        reuse: true
      env:
        ## Auth
        MDB_API_KEY: ${{ secrets.MDB_API_KEY }}
        MDB_API_SECRET: ${{ secrets.MDB_API_KEY }}
        ## MongoDB connection credentials
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        MDB_BASE_URL:  ${{ secrets.MDB_BASE_URL }}
    - run: 
          echo ${{steps.createCluster.outputs.clusterURL}}
